
version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/contact"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/core"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/email_recovery"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/fcm"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/forward"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/model"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/rule_filter"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/server_settings"
    schedule:
      interval: "daily"
